// Auto-generated by ci_post_clone.sh during Xcode Cloud builds.
// For local development, fill in your values below.
// NEVER commit real credentials — the pre-commit hook will block it.
enum SupabaseSecrets {
    static let url = ""
    static let anonKey = ""
}
